// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFpg6KGHSWCKjDbgu_dJGvk_6m-fPtxLk',
    appId: '1:118713280049:web:04de90c06951d9ab359710',
    messagingSenderId: '118713280049',
    projectId: 'chat-app-1f2ed',
    authDomain: 'chat-app-1f2ed.firebaseapp.com',
    storageBucket: 'chat-app-1f2ed.appspot.com',
    measurementId: 'G-YDRTPDF9RB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8jCcxPEOcj7qhXwA0jrx_Xqbt1PQcEhQ',
    appId: '1:118713280049:android:2e5c7f651c255e1d359710',
    messagingSenderId: '118713280049',
    projectId: 'chat-app-1f2ed',
    storageBucket: 'chat-app-1f2ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtLGYYMQa186kNjsiobZhDyZlg4VehJ5g',
    appId: '1:118713280049:ios:70bb55c66dcfc913359710',
    messagingSenderId: '118713280049',
    projectId: 'chat-app-1f2ed',
    storageBucket: 'chat-app-1f2ed.appspot.com',
    iosClientId: '118713280049-75crr3t4u92dnntf9vupccoklhta6un7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtLGYYMQa186kNjsiobZhDyZlg4VehJ5g',
    appId: '1:118713280049:ios:70bb55c66dcfc913359710',
    messagingSenderId: '118713280049',
    projectId: 'chat-app-1f2ed',
    storageBucket: 'chat-app-1f2ed.appspot.com',
    iosClientId: '118713280049-75crr3t4u92dnntf9vupccoklhta6un7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
